# **Pandas**

## Series (1D Labeled Array)

It is strictly one-dimensional, meaning it holds a single list of data. What makes it special is the Index—a built-in label for each item, allowing you to easily look up specific values.

In [ ]:
import pandas as pd

# Creating a Series from a list with custom index labels
temperatures = [22, 24, 19]
days = ['Monday', 'Tuesday', 'Wednesday']

temp_series = pd.Series(data=temperatures, index=days)
print(temp_series)

Monday       22
Tuesday      24
Wednesday    19
dtype: int64

## DataFrames (2D Tabular Data)

A DataFrame is exactly like a full Excel spreadsheet or a database table. It is two-dimensional, meaning it has both rows and columns. In fact, you can think of a DataFrame as a collection of Series glued together side-by-side.

The Concept of Index vs. Columns:

- Index (Rows): The labels running vertically down the left side (identifying each row).
- Columns: The labels running horizontally across the top (identifying what data is in each vertical column).

In [ ]:
import pandas as pd

# Creating a DataFrame from a dictionary
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'London', 'Paris']
}
df = pd.DataFrame(data)
print(df)

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris

## The Core Concept

Think of Data I/O as the doors to your data workflow:
- Input (Reading): Bringing external data into Python so you can explore and change it. This converts your file into a DataFrame (a 2D table, just like a virtual spreadsheet).
- Output (Writing): Sending your cleaned or analyzed DataFrame back out of Python to save it as a file on your computer.

### Reading Data (Input)

These functions usually start with pd.read_... and are used to load a file into a DataFrame variable (commonly named df).
- pd.read_csv(): Reads plain text files separated by commas.
- pd.read_excel(): Reads standard Excel spreadsheets (.xlsx).
- pd.read_json(): Reads JSON files (common in web data).
- pd.read_sql(): Reads the results of a database query.

In [ ]:
df = pd.read_csv('products-100.csv')

### Writing Data (Output)

Once you are done modifying your data, you use methods attached directly to your DataFrame (starting with .to_...) to save it.
- .to_csv(): Saves your table as a new comma-separated file.
- .to_excel(): Saves your table as a new Excel file.
- index=False prevents pandas from writing the row numbers into the file

In [ ]:
df.to_excel("product-olala.xlsx", index=False)

## Viewing Data

These methods help you get a quick peek at the actual values inside your dataset.
- .head(n): Returns the first n rows of the dataset. If you leave n blank, it defaults to 5. Great for seeing what the top of your data looks like.
- .tail(n): Returns the last n rows. Defaults to 5. Useful for verifying that your entire file loaded correctly to the end.
- .sample(n): Returns a random selection of n rows. Defaults to 1.

In [ ]:
# df.head()
print(df.shape)
print(df.size)
df.head()

(100, 13)
1300

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
0,1,Compact Printer Air Advanced Digital,Situation organization these memory much off.,"Garner, Boyle and Flynn",Books & Stationery,265,USD,774,2091465262179,ForestGreen,Large,pre_order,56
1,2,Tablet,Discussion loss politics free one thousand.,Mueller Inc,Shoes & Footwear,502,USD,81,5286196620740,Black,8x10 in,in_stock,29
2,3,Smart Blender Cooker,No situation per.,"Lawson, Keller and Winters",Kitchen Appliances,227,USD,726,1282898648918,SlateGray,XS,in_stock,70
3,4,Advanced Router Rechargeable,For force gas energy six laugh.,Gallagher and Sons,Kitchen Appliances,121,USD,896,3879177514583,PaleGreen,L,discontinued,31
4,5,Portable Mouse Monitor Phone,Feeling back religious however author room sci...,Irwin LLC,Kids' Clothing,1,USD,925,9055773261265,SeaShell,100x200 mm,discontinued,10

## Understanding Structure

These commands tell you about your data size, types, and labels rather than the data values themselves. (Note: attributes like shape, columns, and index do not use parentheses '()').
- .info(): Provides a concise summary of the dataset. It shows the number of rows/columns, the data type of each column (text, integer, decimal), and how many non-blank (non-null) values exist.
- .shape: Returns a tuple showing the dimensions of the data: (number_of_rows, number_of_columns).
- .columns: Returns a list of all the column names. Helpful when you have dozens of columns and need the exact spelling.
- .index: Returns information about the row labels (how the rows are numbered or named).

In [ ]:
df.info()
# df.shape
# df.columns
# df.index

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Index         100 non-null    int64
 1   Name          100 non-null    object
 2   Description   100 non-null    object
 3   Brand         100 non-null    object
 4   Category      100 non-null    object
 5   Price         100 non-null    int64
 6   Currency      100 non-null    object
 7   Stock         100 non-null    int64
 8   EAN           100 non-null    int64
 9   Color         100 non-null    object
 10  Size          100 non-null    object
 11  Availability  100 non-null    object
 12  Internal ID   100 non-null    int64
dtypes: int64(5), object(8)
memory usage: 10.3+ KB

## Summary Statistics

These methods give you a mathematical or categorical summary of the information in your columns.
- .describe(): Calculates quick statistical summaries for all numeric columns (count, mean, standard deviation, min, max, and percentiles).
- .value_counts(): Counts how many times each unique value appears in a specific column. Highly useful for categorical data (like seeing how many people are in each department).

In [ ]:
# df.describe()
df['Size'].value_counts()

Size
L              10
Extra Large     9
8x10 in         9
5x7 in          9
S               8
Medium          7
XXL             6
10x10 cm        6
50x70 cm        5
XL              5
Small           5
Large           4
M               4
12x18 in        4
30x40 cm        3
XS              3
100x200 mm      3
Name: count, dtype: int64

## Column Selection: df['column'] vs. df.column

- df['column'] (Bracket style): This is the safest and most reliable method. It works for any column name, even if the name has spaces (e.g., df['First Name']) or matches a built-in Python function.
- df.column (Attribute style): This is a handy shortcut for typing quickly, but it fails if your column name has spaces, special characters, or shares a name with a pandas method (like .min or .sum).

In [ ]:
import pandas as pd

data = {'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
        'Age': [25, 30, 35, 28],
        'City': ['NY', 'LA', 'Chicago', 'NY']}
df = pd.DataFrame(data)
df.index = ['row1', 'row2', 'row3', 'row4']
print(df)

         Name  Age     City
row1    Alice   25       NY
row2      Bob   30       LA
row3  Charlie   35  Chicago
row4    Diana   28       NY

## Label-based Indexing: .loc[]

- Explanation: Think of .loc as "locate by name." You use the exact text labels of your rows and columns to find data.
- Key rule: When you slice with .loc (e.g., A:C), it includes the last item.

In [ ]:
import pandas as pd

data = {'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
        'Age': [25, 30, 35, 28],
        'City': ['NY', 'LA', 'Chicago', 'NY']}
df = pd.DataFrame(data)
df.index = ['row1', 'row2', 'row3', 'row4']
print(df)
print("\n")
print(df.loc[['row1','row3'],['Name','City']])

         Name  Age     City
row1    Alice   25       NY
row2      Bob   30       LA
row3  Charlie   35  Chicago
row4    Diana   28       NY


         Name     City
row1    Alice       NY
row3  Charlie  Chicago

## Integer-based Indexing: .iloc[]

- Explanation: Think of .iloc as "locate by index (number)." You use the numerical position (0, 1, 2...) exactly like you would with standard Python lists.
- Key rule: When you slice with .iloc (e.g., 0:2), it goes up to but does not include the last number.

In [ ]:
import pandas as pd

data = {'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
        'Age': [25, 30, 35, 28],
        'City': ['NY', 'LA', 'Chicago', 'NY']}
df = pd.DataFrame(data)
df.index = ['row1', 'row2', 'row3', 'row4']
print(df)
print("\n")
print(df.iloc[0:2, 0:1])

         Name  Age     City
row1    Alice   25       NY
row2      Bob   30       LA
row3  Charlie   35  Chicago
row4    Diana   28       NY


       Name
row1  Alice
row2    Bob

## Filtering (Boolean Conditions)

- Explanation: You can filter a DataFrame by passing true/false conditions inside the brackets [].
- Key rule: When combining multiple conditions, you must wrap each condition in parentheses () and use the bitwise operators & (and), | (or), and ~ (not). Standard Python and/or keywords will not work here.

In [ ]:
import pandas as pd

data = {'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
        'Age': [25, 30, 35, 28],
        'City': ['NY', 'LA', 'Chicago', 'NY']}
df = pd.DataFrame(data)
df.index = ['row1', 'row2', 'row3', 'row4']
print(df)
print("\n")
older_than_28 = df['Age'] > 28
# print(df[older_than_28])
older_than_25_in_NY = (df['Age'] >= 25) & (df['City'] == 'NY')
# print(df[older_than_25_in_NY])
# older_than_25_or_in_NY = (df['Age'] > 28) | (df['City'] == 'LA')
# print(df[older_than_25_or_in_NY])
not_NY = ~(df['City']=='NY')
print(df[not_NY])

         Name  Age     City
row1    Alice   25       NY
row2      Bob   30       LA
row3  Charlie   35  Chicago
row4    Diana   28       NY


         Name  Age     City
row2      Bob   30       LA
row3  Charlie   35  Chicago